FrontEnd/Pages/Admin/AddAdmin.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Aplicacion.App.Dominio;
using Aplicacion.App.Persistencia;

namespace FrontEnd.Pages
{
     public class AddAdminModel : PageModel
    {
        [BindProperty]
        public Estacion estacion {get;set;}
        [BindProperty]
        public TecnicoMantenimiento tecnico{get;set;}

        public static IRepositorioValidacion _repoValidacion=new RepositorioValidacion(new Aplicacion.App.Persistencia.AppContext());
        public static IRepositorioTecnicoMantenimiento _repoTecnico=new RepositorioTecnicoMantenimiento(new Aplicacion.App.Persistencia.AppContext());
        public static IRepositorioEstacion _repoEstacion=new RepositorioEstacion(new Aplicacion.App.Persistencia.AppContext());
    
        public IActionResult OnGet()
        {
            if(_repoValidacion.GetValidacion(1).Val!=1)
            {
                return RedirectToPage("InicioAdmin");
            }
            else
            {   
                _repoValidacion.UpdateValidacion(1,0);
                return Page(); 
            }   
        }
        public void OnPost()
        {   
        }
        public void OnPostCrearEstacion()
        {   
            _repoEstacion.AddEstacion(estacion);
        }
        public void OnPostCrearTecnico()
        {   
            _repoTecnico.AddTecnicoMantenimiento(tecnico);
        }
    }
}

FrontEnd/Pages/Admin/InicioAdmin.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Aplicacion.App.Persistencia;
using Aplicacion.App.Dominio;

namespace FrontEnd.Pages
{
    public class InicioAdminModel : PageModel
    {
        //public int validacion=0;
        [BindProperty]
        public Administrador administrador {get;set;}
        [TempData]
        public string nombre{get;set;}
        //public static Validacion validacion=new Validacion();
        //public static Administrador administrador=new Administrador();
        public static IRepositorioAdministrador _repoAdministrador=new RepositorioAdministrador(new Aplicacion.App.Persistencia.AppContext());
        public static IRepositorioValidacion _repoValidacion=new RepositorioValidacion(new Aplicacion.App.Persistencia.AppContext());
    
        public void OnGet()
        {
            nombre="";
        }
        public void OnPost()
        {
        }
        public IActionResult OnPostIngresar()
        {
            string url="";
            administrador=_repoAdministrador.GetAdministrador(administrador);
            if(administrador!=null)
            {
                nombre=administrador.Nombres+" bienvenido";
                _repoValidacion.UpdateValidacion(1,1);
                url="AddAdmin";

            }
            else
            {
               _repoValidacion.UpdateValidacion(1,0);
               nombre="datos erroneos"; 
               
            }
            return RedirectToPage(url);
        }
    }
}

FrontEnd/Pages/Admin/InicioAdmin.cshtml
@page
@model FrontEnd.Pages.InicioAdminModel
@{
}
<h1 class="display-6 encabezado">ADMINISTRADOR</h1><br>
<div class="container bloque bloque_list">
    <form class="d-flex row g-2 col-md-5 " method="POST">
        <div class="row">
            <label for="InicioAdminIdentificacion" class="form-label col-md-4 ">IDENTIFICACION </label>
            <input class="col-md-8 " asp-for="@Model.administrador.Identificacion" id="InicioAdminIdentificacion"
                placeholder="Identificacion">
        </div>
        <div></div>
        <div class="row">
            <label for="InicioAdminPassword" class="form-label col-md-4">CONTRASEÑA</label>
            <input class="col-md-8 " asp-for="@Model.administrador.Password" id="InicioAdminPassword"
                placeholder="contraseña">
        </div>
        <div></div>
        <h3  class="display-6">@Model.nombre</h1>
        <div class="row">
            <div class="col-md-1"></div>
            <input class="col-md-2" type="submit" value="crear" asp-page-handler="Ingresar">
        </div>
    </form>
</div>