FrontEnd/Pages/Reportes/AddDatMet.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Aplicacion.App.Persistencia;
using Aplicacion.App.Dominio;

namespace FrontEnd.Pages
{
    public class AddDatMetModel : PageModel
    {
        [BindProperty]
        public Estacion estacion {get;set;}
        [BindProperty]
        public TecnicoMantenimiento tecnico{get;set;}
        [BindProperty]
        public DatoMeteorologico dato {get;set;}
        [TempData]
        public string codigoestacion{get;set;}
        [TempData]
        public string mensajeerror{get;set;}
        public static IRepositorioEstacion _repoEstacion=new RepositorioEstacion(new Aplicacion.App.Persistencia.AppContext());
        public static IRepositorioTecnicoMantenimiento _repoTecnico=new RepositorioTecnicoMantenimiento(new Aplicacion.App.Persistencia.AppContext());
        //public static IRepositorioDato _repoDato=new RepositorioDato(new MonitoreoMeteorologico.App.Persistencia.AppContext());
    
        public void OnGet()
        {
            estacion=_repoEstacion.GetEstacion(codigoestacion);
            mensajeerror = "";
        }
        public void OnPost()
        {

        }
        public void OnPostAsigTec()
        {
            estacion = _repoEstacion.GetEstacion(estacion.Codigo);
            if (estacion != null)
            {
                tecnico = _repoTecnico.GetTecnicoMantenimiento(tecnico.Identificacion);
                if (tecnico != null)
                {
                    _repoEstacion.AsignarTecnico(estacion.Codigo, tecnico);
                    mensajeerror = "Operacion Exitosa";
                }
                else{
                    mensajeerror = "Técnico no existe";
                }
            }
            else{
                mensajeerror = "Estación no existe";
            }
        }
    }
}

FrontEnd/Pages/Reportes/InicioReporte.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Aplicacion.App.Persistencia;
using Aplicacion.App.Dominio;

namespace FrontEnd.Pages
{
    public class InicioReporteModel : PageModel
    {
        [BindProperty]
        public Estacion estacion {get;set;}
        [BindProperty]
        public TecnicoMantenimiento tecnico{get;set;}
        [TempData]
        public int identec{get;set;} 
        [TempData]
        public string codigoestacion{get;set;}
        public static IRepositorioEstacion _repoEstacion=new RepositorioEstacion(new Aplicacion.App.Persistencia.AppContext());
        public static IRepositorioTecnicoMantenimiento _repoTecnico = new RepositorioTecnicoMantenimiento(new Aplicacion.App.Persistencia.AppContext());
    
        public void OnGet()
        {
            codigoestacion="";
        }
        public void OnPost()
        {

        }
        public IActionResult OnPostConsultarEstacion()
        {   
           string url="";
           estacion=_repoEstacion.GetEstacion(estacion.Codigo);
           if(estacion!=null)
           {
               codigoestacion=estacion.Codigo;
               url="AddDatMet";
           }
           else
           {
                codigoestacion="";
                url="";
           }
           return RedirectToPage(url);
        }
        public IActionResult OnPostConsultarTecnico()
        {   
           string url="";
           tecnico = _repoTecnico.GetTecnicoMantenimiento(tecnico.Identificacion);
           if(tecnico!=null)
           {
               identec=tecnico.Identificacion;
               url="ReporteTecnico";
           }
           else
           {
                identec=0;
                url="";
           }
           return RedirectToPage(url);
        }
    }
}

FrontEnd/Pages/Reportes/AddDatMet.cshtml
@page
@model FrontEnd.Pages.AddDatMetModel
@{
}
<h1></h1>
<h3 class="display-6">@Model.codigoestacion</h1><br>

<div class="container bloque bloque_list">
    <form class="d-flex row g-2 col-md-5 " method="POST">
        <div class="row">
            <label for="AddDatMetCodigo" class="form-label col-md-4 ">CÓDIGO </label>
            <input class="col-md-8 " asp-for="@Model.estacion.Codigo" id="AddDatMetCodigo"
                placeholder="Código">
        </div>
        <div></div>
        <div class="row">
            <label for="AddDatMetIdent" class="form-label col-md-4">IDENTIFICACIÓN</label>
            <input class="col-md-8 " asp-for="@Model.tecnico.Identificacion" id="AddDatMetIdent"
                placeholder="Identificación">
        </div>
        <div></div>
        <div class="row">
            <div class="col-md-1"></div>
            <input class="col-md-2" type="submit" value="Asignar Ténico" asp-page-handler="AsigTec">
        </div>
    </form>
</div>
<h1 class="display-6">@Model.mensajeerror</h1>

FrontEnd/Pages/Reportes/InicioReporte.cshtml
@page
@model FrontEnd.Pages.InicioReporteModel
@{
}
<h1 class="display-6 encabezado">REPORTES</h1><br>
<div class="container bloque bloque_list">
  <form class="d-flex row g-2 col-md-5 " method="POST">
    <h3 class="display-6">Estación</h1>
    <div></div>
    <div class="row">
      <label for="InicioReporteCodEstacion" class="form-label col-md-6 ">CODIGO </label>
      <input class="col-md-6" asp-for="@Model.estacion.Codigo" id="InicioReporteCodEstacion"
        placeholder="Codigo Estación">
    </div>
    <div></div>
    <h3 class="display-6">@Model.codigoestacion</h3>
    <div class="row">
      <div class="col-md-1"></div>
      <input class="col-md-4" type="submit" value="Consultar" asp-page-handler="ConsultarEstacion">
    </div>
  </form>
<div>
<div class="container bloque bloque_list">  
  <form class="d-flex row g-2 col-md-5 " method="POST">
    <h3 class="display-6">Técnico</h1><br>
    <div class="row">
      <label for="InicioReporteIdenTec" class="form-label col-md-6">Identificación Técnico </label>
      <input class="col-md-6" asp-for="@Model.tecnico.Identificacion" id="InicioReporteIdenTec"
        placeholder="Identificación Técnico">
    </div>
    <div></div>
    <h3 class="display-6">@Model.identec</h3>
    <div class="row">
      <div class="col-md-1"></div>
      <input class="col-md-4" type="submit" value="Consultar" asp-page-handler="ConsultarTecnico">
    </div>
  </form>
</div>